# Generated by Django 4.1.1 on 2022-09-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPagEntreg', '0002_remove_juegos_genero_remove_libros_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegos',
            name='puntaje',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='libros',
            name='puntaje',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='puntaje',
            field=models.IntegerField(default=1),
        ),
    ]
